export const kingdoms = {
  baekje: { name: '백제', color: '#b66b32' },
  goguryeo: { name: '고구려', color: '#42625b' },
  silla: { name: '신라', color: '#7763a1' },
};
export const places = [
  { id: 'pyeongyang', name: '평양', modern: '오늘날 평양 일대', coordinates: [125.75, 39.03], dx: 15, dy: -10, note: '371년 백제의 공격 대상. 고구려의 평양 천도는 그 뒤인 427년입니다.' },
  { id: 'hanseong', name: '한성', modern: '오늘날 서울 한강 남쪽 일대', coordinates: [127.11, 37.53], dx: -18, dy: -20, anchor: 'end', note: '백제 초기의 수도권. 475년 고구려의 공격으로 함락되었고 백제는 웅진으로 옮깁니다.' },
  { id: 'upperHan', name: '한강 상류 방면', modern: '오늘날 충주를 포함한 상류권', coordinates: [127.93, 37.0], dx: 18, dy: -4, note: '551년 신라가 확보한 한강 상류 10군의 정확한 경계는 불명확합니다. 이 표시는 상류 방면을 가리킵니다.', region: true },
  { id: 'ungjin', name: '웅진', modern: '오늘날 공주', coordinates: [127.12, 36.46], dx: -16, dy: -5, anchor: 'end', note: '475년 한성 함락 뒤 백제가 옮긴 수도. 성왕은 538년에 다시 사비로 천도합니다.' },
  { id: 'sabi', name: '사비', modern: '오늘날 부여', coordinates: [126.92, 36.28], dx: -16, dy: 18, anchor: 'end', note: '성왕이 538년 옮긴 백제의 수도. 551~554년의 백제 수도는 웅진이 아니라 사비입니다.' },
  { id: 'geumseong', name: '금성', modern: '오늘날 경주', coordinates: [129.22, 35.83], dx: 15, dy: 3, note: '신라의 수도. 진흥왕 때 신라는 한강 상류에 이어 하류까지 확보합니다.' },
  { id: 'gwansan', name: '관산성', modern: '오늘날 충북 옥천 일대', coordinates: [127.58, 36.30], dx: 19, dy: 15, note: '554년 백제 성왕이 전사한 전투의 무대입니다. 한강 유역과 구별해야 하며 정확한 전투 지점·비정에는 논의가 있습니다.' },
];
export const steps = [
  { id: 'baekje-4c', year: '4세기', date: '근초고왕 · 371년', title: '한강의 나라, 백제가 북으로 나아가다', short: '백제의 성장', kingdom: 'baekje', focus: ['hanseong','pyeongyang'], route: [{from:'hanseong',to:'pyeongyang',kingdom:'baekje',label:'북진·평양 공격',bend:-35}], why: '한강 유역을 기반으로 성장한 백제는 북쪽의 고구려와 세력을 겨루었습니다.', change: '근초고왕은 371년 평양성을 공격했습니다. 한강의 백제가 북방까지 공세를 펼친 장면입니다.', result: '이때의 평양은 백제가 차지한 수도가 아닙니다. 공격과 영구 점유를 구별하세요.', river: '한강을 기반으로 성장한 백제', compare: { baekje:'근초고왕 · 평양 공격',goguryeo:'고국원왕 · 전사',silla:'내물왕 · 성장기' }, question:'백제의 출발점은 어디였을까요?', capital:'한성', sources:["https://encykorea.aks.ac.kr/Article/E0007465", "https://encykorea.aks.ac.kr/Article/E0005300"] },
  { id: 'goguryeo-475', year: '475년', date: '장수왕 · 남진', title: '고구려가 한성을 함락하다', short: '고구려의 남진', kingdom:'goguryeo',focus:['pyeongyang','hanseong','ungjin'],route:[{from:'pyeongyang',to:'hanseong',kingdom:'goguryeo',label:'장수왕의 남진',bend:35},{from:'hanseong',to:'ungjin',kingdom:'baekje',label:'백제, 웅진 천도',bend:35,dashed:true}],why:'427년 평양으로 천도한 고구려는 남쪽으로 압력을 높였습니다.',change:'475년 장수왕이 한성을 함락했습니다. 백제 개로왕이 죽고, 문주왕은 수도를 웅진으로 옮겼습니다.',result:'한강을 잃은 백제는 남쪽에서 재건해야 했습니다. 지도에서 한성→웅진의 이동을 따라가 보세요.',river:'고구려의 한강 진출',compare:{baekje:'개로왕 전사 → 문주왕',goguryeo:'장수왕 · 한성 함락',silla:'자비왕 · 나제 동맹기'},question:'한성을 잃은 백제는 어디로 옮겼을까요?',capital:'웅진',sources:["https://encykorea.aks.ac.kr/Article/E0048605", "https://encykorea.aks.ac.kr/Article/E0019671"]},
  {id:'alliance-551',year:'551년',date:'성왕 + 진흥왕',title:'백제와 신라가 함께 한강으로 진출하다',short:'나제 연합의 반격',kingdom:'baekje',focus:['sabi','geumseong','hanseong','upperHan'],route:[{from:'sabi',to:'hanseong',kingdom:'baekje',label:'백제 → 하류',bend:-55},{from:'geumseong',to:'upperHan',kingdom:'silla',label:'신라 → 상류',bend:35}],why:'고구려의 남진에 맞서 협력해 온 백제와 신라는 연합 공격에 나섰습니다.',change:'백제는 한강 하류 6군을, 신라는 상류 10군을 확보했습니다. 같은 한강이지만 얻은 지역은 달랐습니다.',result:'성왕의 백제 수도는 이미 사비였습니다(538년 천도). 하류·상류의 분담이 다음 갈등의 배경이 됩니다.',river:'하류 백제 · 상류 신라',compare:{baekje:'성왕 · 하류 회복',goguryeo:'양원왕 · 한강 지역 상실',silla:'진흥왕 · 상류 확보'},question:'신라가 얻은 쪽은 상류일까요, 하류일까요?',capital:'사비',sources:["https://contents.history.go.kr/mobile/kc/view.do?code=kc_age_10&levelId=kc_n101190", "https://contents.history.go.kr/front/nh/print.do?levelId=nh_005_0030_0040&whereStr="]},
  {id:'silla-553',year:'553년',date:'진흥왕 · 한강 하류 확보',title:'신라가 백제의 하류까지 차지하다',short:'신라의 한강 확보',kingdom:'silla',focus:['hanseong','upperHan','geumseong','sabi'],route:[{from:'upperHan',to:'hanseong',kingdom:'silla',label:'상류에서 하류로',bend:45}],why:'상류를 확보한 신라는 서쪽의 한강 하류로 세력을 넓혔습니다.',change:'553년 신라는 백제가 회복했던 하류 지역까지 확보했습니다. 551년 연합했던 두 나라가 이제 맞섭니다.',result:'한강 유역 확보는 중부의 교통로와 서해 방면 진출에 유리했습니다. 백제와 신라의 관계는 전쟁으로 치닫습니다.',river:'신라, 상류에 이어 하류까지',compare:{baekje:'성왕 · 하류 상실',goguryeo:'양원왕',silla:'진흥왕 · 하류 확보'},question:'551년 지도에서 무엇이 달라졌나요?',capital:'사비',sources:["https://contents.history.go.kr/front/nh/print.do?levelId=nh_005_0030_0040&whereStr="]},
  {id:'gwansan-554',year:'554년',date:'성왕 · 관산성 전투',title:'갈등은 관산성의 전투로 이어지다',short:'관산성 전투',kingdom:'silla',focus:['gwansan','sabi','geumseong'],route:[{from:'sabi',to:'gwansan',kingdom:'baekje',label:'백제의 공격',bend:-35,labelDy:-4},{from:'geumseong',to:'gwansan',kingdom:'silla',label:'신라의 대응',bend:30,labelDy:36}],why:'한강 하류를 잃은 백제는 신라와 전쟁을 벌였습니다.',change:'554년 관산성 전투에서 백제 성왕이 전사했습니다. 전투 무대는 한강이 아닌 오늘날 충북 옥천 일대입니다.',result:'나제 동맹의 붕괴와 신라의 성장을 연결해 보세요. “한강을 둘러싼 갈등”과 “실제 전투 장소”는 같지 않습니다.',river:'한강 확보를 둘러싼 갈등의 여파',compare:{baekje:'성왕 · 관산성에서 전사',goguryeo:'양원왕',silla:'진흥왕 · 백제와 전쟁'},question:'관산성은 한강과 얼마나 떨어져 있나요?',capital:'사비',sources:["https://contents.history.go.kr/front/hm/view.do?levelId=hm_010_0050", "https://encykorea.aks.ac.kr/Article/E0004868"]},
];
export const mapQuestions = [
 {id:'capital',step:1,prompt:'475년 한성이 함락되었습니다. 백제가 수도를 옮긴 곳을 지도에서 골라 보세요.',answer:'ungjin',explanation:'웅진(공주)입니다. 한성→웅진은 475년, 웅진→사비는 538년입니다. 수도가 바뀐 이유와 위치를 함께 기억하세요.'},
 {id:'upstream',step:2,prompt:'551년 연합 공격에서 신라가 확보한 방면을 지도에서 골라 보세요.',answer:'upperHan',explanation:'신라는 한강 상류 10군, 백제는 하류 6군을 확보했습니다. 표시한 점은 상류 방면이며 정확한 10군의 경계는 아닙니다.'},
 {id:'battle',step:4,prompt:'554년 백제 성왕이 전사한 전투 장소를 지도에서 골라 보세요.',answer:'gwansan',explanation:'관산성(충북 옥천 일대)입니다. 한강을 둘러싼 갈등이 원인이 되었지만, 전투가 한강변에서 벌어진 것은 아닙니다.'},
];
